### ISSUE TITLE
not showing anything when i start it

### ISSUE THREAD

**Issue by bashon1** [wdesgardin/speedometer#1]
Hello
thanks for sharing it
i use esx 1.2
showing anything when i start it

**Comment by wdesgardin** [comment]
Hello,

Maybe you're not using "esx_legacyfuel". I added a check so that the interface is displayed even if this resource is not executed. 

Let me know if this fixes your problem, otherwise please try to provide some error logs.

**Comment by bashon1** [comment]
am using 
https://github.com/InZidiuZ/LegacyFuel
with your new Update now it working will, thank you

**Comment by wdesgardin** [comment]
Alright, if you want the fuel indicator to work with this ressource, juste replace exports["esx_legacyfuel"] by exports["LegacyFuel"] in [client.lua](https://github.com/wdesgardin/speedometer/blob/fda78f3796f9bc4e54d4e73374a4b8a1cc04d985/client.lua#L28)
